#!/bin/bash
source fun.sh
echo -e "${BLUE}${BOLD}Cette operation vas installer tout les prérequis pour le bon fonctionnement du script ${NC}"
echo -e "${RED}${BOLD}${UNDERLLINE}Il se peux que vous devez saisir votre mot de passe machine pour une premiere fois ! ${NC}"
sudo apt update
clear
logo
sudo apt install zip
logo
clear 
logo
sudo apt install tree
clear
